on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Bot build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build bot
        run: docker-compose up --build
