name: Java CI

on: 
  push: 
    branches: [main]
    tags: ['v*']
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: discraft.jar build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Save discraft.jar
        run: mkdir plugin && cp target/discraft*.jar plugin
      - name: Upload .jar
        uses: actions/upload-artifact@v3
        with:
          name: discraft.jar
          path: plugin
      - name: Save tests results
        run: mkdir tests && cp -R target/site/jacoco tests
      - name: Upload tests results
        uses: actions/upload-artifact@v3
        with:
          name: tests results
          path: tests
