name: Docker images CI 

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Bot build
    steps:
      - name: Checkout
        uses: actions/checkout@v3  
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: nanamyyu/discraft-repo
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./bot
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
